title: "Toolb 发现"
description: "你的精选视频集合地"
permalink: /:title/
theme-color: "#fa4694"
gravatar: 146924576b3eec83130f224495cdbedc

reddit: imgradeone
twitter: imgradeone

authors:
  imgradeone:
    name: "imgradeone"
  annoymous:
    name: "imgradeone"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 7
paginate_path: "/archive/:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]
